[package]
name = "util"
version = "2.0.0-beta.0"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
publish = false

[dependencies]
tauri.workspace = true
