[package]
name = "tauri-plugin-tauri"
version = "2.0.0-beta.0"
description = "Tauri is a reserved Tauri plugin name"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true

[dev-dependencies]
util.workspace = true
